routes/web.php
<?php

use App\Http\Controllers\InvitationController;
use App\Http\Controllers\UserInfoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('/', 'welcome');

Route::view('dashboard', 'dashboard')
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

Route::view('profile', 'profile')
    ->middleware(['auth'])
    ->name('profile');

Route::view('invitation', 'invitation')->middleware(['auth'])->name('invitation');

Route::get('/userinfo', [UserInfoController::class, 'getUserInfo'])->middleware(['auth'])->name('userinfo');

Route::get('.well-known/openid-configuration', function () {
    
        return response()->json([
            'issuer' => 'https://auth.local',
            'authorization_endpoint' => 'https://auth.local/oauth/authorize',
            'token_endpoint' => 'http://auth.local/oauth/token',
            'userinfo_endpoint' => 'http://auth.local/api/user',
            'jwks_uri' => 'http://auth.local/.well-known/jwks'
        ]);
    });

Route::get('.well-known/jwks', function () {
    return response()->json([
        "keys" => [
            [
            "kty" => "RSA",
            "n" => "yCqojB4h7vlL1lE41R2003QBpPXDRCkIL3Ia4Xba8HTnw5W6GlX23cIu92En_TWtW0RwUc6VBWoW4523k9DqUEerDEGKe9h5ivzTogv-wOxSxToAB0yU4ZetP0kWIAvTNspPwvH-n-oLvQTPTgt5MCV0aNOC97dI52-5ctUykdoopKoS0Em6ACPzwHPFyX-NhCcLOe-tMbpvQvCWopxjUPvlLVCt5QZOJPyFdJvpltxFqpuKflZ98QLi9_I6RUN4Bty0YF7ndx82tH5OLe0CvqJ3uwWptMoV6uHYA2zhiGhCS3Rm1UjR-Vmm88yRO7m5ubNzEeEaGlK-RMySAcnf3WnjSVTOba7w56RqFgNuitHRXdM0ATyoozEZ0iYsFXe5et25P57ny9HuE5eHFlAEMl6Piv0BZ63Q9oIMNx-8_iRYdwjCzMgD5DCE5jk34Zj1FTh9YN-5Obq2olEbqpzxWQQC4hb0zNKPVWwhIUwTDvsTj5u7Bhp-cMX3XmeOZfKVUKzxvGk9kJ0yLO2JUS242cN_NqPUpZqKO3oYcilg2ZO8LCBArStB8da99OFR4FyYv-4yUFTbKeWbIIYBnkmFbRNA7k-W6qCnCi1kPkiPA2_BfVJk42U9cvwetGw6Wp-WD6786JHWOjVrwxpI_Zjb1WxbXioxJcDHZEjsspfvzGc",
            "e" => "AQAB",
            "alg" => "RS256",
            "use" => "sig",
            'kid' => base64_encode('public-key-added-2023-01-01')
            ]
        ]
    ]);
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/invitation.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Invitations') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <x-profile-card title="Send invitation" subtitle="Send an invitation to a friend">
                <livewire:create-invitation />
            </x-profile-card>            

            <x-profile-card title="Pending invitations" subtitle="Lorem ipsum">
                <livewire:invitation-table status='pending' />
            </x-profile-card>

            <x-profile-card title="Accepted invitations" subtitle="Lorem ipsum">
                <livewire:invitation-table status="accepted"/>
            </x-profile-card>

        </div>
    </div>
</x-app-layout>

resources/views/profile.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Profile') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.update-profile-information-form />
                </div>
            </div>

            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.update-password-form />
                </div>
            </div>

            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.delete-user-form />
                </div>
            </div>
        </div>
    </div>
</x-app-layout>